[package]
name = "toyc"
version = "0.1.0"
authors = ["tarberd <bernardo.mferrari@gmail.com>"]
edition = "2018"

[dependencies]
toy-parser = { path = "../toy-parser" }
llvm-sys = "100"
structopt = "0.3.12"
